# Generated by Django 2.2.16 on 2020-09-28 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoastOrRoast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=240)),
                ('is_boast', models.BooleanField(blank=True, default=False)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('up_votes', models.IntegerField(default=0)),
                ('down_votes', models.IntegerField(default=0)),
                ('vote_score', models.IntegerField(default=0)),
            ],
        ),
    ]
